spring.application.name=convexa-ai-backend

# ===============================
# DATABASE CONFIG
# ===============================


spring.datasource.url=jdbc:postgresql://ep-ancient-night-aojl1cz9-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Papo5FOfeDx3

spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
# ===============================
# FILE UPLOAD CONFIG
# ===============================

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


# ===============================
# CLOUDINARY CONFIG
# ===============================

cloudinary.cloud-name=doydgo6zc
cloudinary.api-key=648822799431629
cloudinary.api-secret=rgb1vITV5iZm2zCVbRdcP46VcX4

# ===============================
# SERVER CONFIG
# ===============================

server.port=8080

ai.service.url=http://127.0.0.1:8000
google.client.id=206628039286-2aoqiq47vmbgaee75tf6al0g53e8prq8.apps.googleusercontent.com