spring.application.name=convexa-ai-backend

# ===============================
# DATABASE CONFIG
# ===============================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
# ===============================
# FILE UPLOAD CONFIG
# ===============================

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


# ===============================
# CLOUDINARY CONFIG
# ===============================

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# ===============================
# SERVER CONFIG
# ===============================

server.port=8080


google.client.id=${GOOGLE_CLIENT_ID}